worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

directory-write-rps: 10
directory-files-cache-ttl-seconds: 30
secdist-path: /app/directory_service/configs/secure_data.docker.json

postgress-connection: postgresql://postgres:postgres@postgres:5432/directory_service
