components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        fs-task-processor:
            worker_threads: $worker-fs-threads
    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard
        dynamic-config: {}
        testsuite-support: {}

        http-client:
        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-directory-list:
            path: /v1/directories
            method: GET
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        handler-directory-create:
            path: /v1/directories
            method: POST
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        handler-directory-get:
            path: /v1/directories/{directory_id}
            method: GET
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        handler-directory-update:
            path: /v1/directories/{directory_id}
            method: PUT
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        handler-directory-delete:
            path: /v1/directories/{directory_id}
            method: DELETE
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        handler-directory-move:
            path: /v1/directories/{directory_id}/move
            method: POST
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        handler-directory-files-list:
            path: /v1/directories/{directory_id}/files
            method: GET
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: protected-handler-pipeline-builder

        directory-repository: {}

        directory-database:
            dbconnection: $postgress-connection
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        jwt-credentials:
            # Store secret in configs instead of env
            # just for the sake of simplicity
            secret: super-secret-jwt-key
            issuer: user-service

        auth-middleware: {}

        protected-handler-pipeline-builder: {}
