worker-threads: 2
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8083
file-write-rps: 100000
file-cache-ttl-seconds: 300
secdist-path: ./file_service/configs/secure_data.json
mongo-connection: mongodb://localhost:27217/admin
